import CarouselSection from "@/components/sections/CarouselSection";
import DifferentiatorSection from "@/components/sections/DifferentiatorSection";
import FactsSection from "@/components/sections/FactsSection";
import FooterSection from "@/components/sections/FooterSection";
import GutterSection from "@/components/sections/GutterSection";
import NavigationSection from "@/components/sections/NavigationSection";
import PartnerLogosSection from "@/components/sections/PartnerLogosSection";
import QuotesSection from "@/components/sections/QuotesSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello, World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationSection />
      <CarouselSection />
      <DifferentiatorSection />
      <PartnerLogosSection />
      <FactsSection />
      <QuotesSection />
      <FooterSection />
      <GutterSection />
    </>
  );
}
